### ISSUE TITLE
Setup Debug mode for VisualStudio Code

### ISSUE THREAD

**Issue by deyanzz** [hiero-ledger/hiero-sdk-cpp#159]
### Problem

Currently, the C++ SDK doesn't have setup for **Debug** mode. It's running only in **Release** mode.
Because of that, it's very hard to debug the logic of the SDK or to trace how exactly it works.

**(Duplicates [Issue #154](https://github.com/hashgraph/hedera-sdk-cpp/issues/154))**

### Solution

1. Setup the following JSON configuration files:
 - **launch.json**
 - **settings.json**
 - **tasks.json**

2. Add new build preset in **CMakePresets.json**:
 `{
      "name": "macos-arm64-debug",
      "inherits": ["vcpkg-base-debug"],
      "cacheVariables": {
        "VCPKG_TARGET_TRIPLET": {
          "type": "STRING",
          "value": "arm64-osx"
        }
      }
    }`

3. Configure the **includePath** for the examples.

### Alternatives

To use **CLion** as an IDE.

**Comment by nathanklick** [comment]
@deyanzz We have an open PR #155 which enables debug builds on Linux with MacOS and Windows support coming shortly.

**Comment by rwalworth** [comment]
> Thanks for noticing it, @nathanklick. I'm watching PR [#155](https://github.com/hashgraph/hedera-sdk-cpp/pull/155) and will close this issue once it's merged into **main** branch.

#155 has been merged.

**Comment by deyanzz** [comment]
Closing it as duplicate of PR [#155](https://github.com/hashgraph/hedera-sdk-cpp/pull/155).
