### ISSUE TITLE
Integration tests for `EthereumTransaction`

### ISSUE THREAD

**Issue by deyanzz** [hiero-ledger/hiero-sdk-cpp#303]
### Problem

`EthereumTransaction` is missing integration tests which were skipped during [PR #299](https://github.com/hashgraph/hedera-sdk-cpp/pull/299).

### Solution

To add proper Integration tests for `EthereumTransaction`

### Alternatives

N/A

**Comment by gsstoykov** [comment]
https://github.com/hiero-ledger/hiero-sdk-cpp/blob/50b6f548ddcc6bb953e548469fe0489995296ce7/src/sdk/tests/integration/EthereumTransactionIntegrationTests.cc test already implemented.
