### ISSUE TITLE
Full implementation for `TransactionReceiptQuery`

### ISSUE THREAD

**Issue by deyanzz** [hiero-ledger/hiero-sdk-cpp#328]
For reference see [TransactionReceiptQuery.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java)

**Comment by rwalworth** [comment]
Going to close as `TransactionReceiptQuery` has been fully implemented in other PRs.
